<a href="https://colab.research.google.com/github/HyungjooAhn1/MachineLearning/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EB%8F%85%ED%95%99_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 넘파이 ndarray 개요

In [1]:
import numpy as np

array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(3,)


In [2]:
array2 = np.array([[1,2,3],[2,3,4]])
print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [3]:
array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(1, 3)


In [4]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim)) ## 차원 확인 ndim

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [5]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype) ## 숫자로 입력했던 1과 2가 문자열 값으로 변환됨.

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype) ## 마찬가지로 int형이 float형으로 바뀜.

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
array_int = np.array([1,2,3]) 
array_float = array_int.astype('float64') ## astype 활용하여 데이터 타입 변경하기 (메모리 절약 위해 보통 이용됨)
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32') ## 정수형으로 바뀌면서 소수점 이하 없어짐.
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [8]:
sequence_array = np.arange(10) ## arange는 range와 유사한 기능. 
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
zero_array = np.zeros((3,2), dtype='int32') ## dtype의 기본값은 float64
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) ## dtype 설정 안해주니 float64임을 알 수 있음.
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### ndarray의 차원과 크기를 변경하는 reshape()

In [11]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
array1.reshape(4,3) ## 오류 발생 >> (4,3) Shape 형태로 변경 불가하기 때문.

ValueError: ignored

In [14]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) ## 인자에 -1 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해준다. 자동으로 (2,5)로 바뀌었다.
print('array2:', array2.shape)

array3 = array1.reshape(5,-1)
print('array3:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2: (2, 5)
array3: (5, 2)


In [15]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) ## tolist()를 통해 리스트 자료형으로 변환

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1) ## 반드시 1개의 칼럼을 가진 ndarray로 변환
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


#### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

In [20]:
## 단일 값 추출

array1 = np.arange(start=1, stop=10) ## start부터 stop-1 까지 생김.
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value)) ## ndarray 타입이 아닌 ndarray 내의 데이터 값을 의미함

print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두 번째 값', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 , 맨 뒤에서 두 번째 값 8


In [21]:
array1[0] = 9
array1[8] = 0
print('array1:', array1) ## 단일 인덱스를 통해 ndarray 내의 데이터값 수정 가능

array1: [9 2 3 4 5 6 7 8 0]


In [23]:
## 다차원 ndarray에서 단일 값 추출

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

## axis 0은 로우 방향의 축, axis 1은 칼럼 방향의 축을 의미한다
## 3차원의 경우 axis 0, axis 1, axis 2로 3개의 축을 가진다

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


##### 슬라이싱은 : 기호 사용

In [24]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [28]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] ## 시작 인덱스 생략하면 자동으로 0으로 간주
print(array4)

array5 = array1[3:] ## 종료 인덱스 생략하면 자동으로 맨 마지막 인덱스로 간주
print(array5)

array6 = array1[:] ## 시작/종료 인덱스 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
## 2차원 ndarray에서의 슬라이싱

array2d = array1.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])
print('array2d[:2,0] \n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[1:3,0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:] 
 [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:] 
 [[2 3]
 [5 6]]
array2d[:2,0] 
 [1 4]


In [30]:
## 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray로 반환
## 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray로 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


##### 팬시 인덱싱(Fancy Indexing)

In [33]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3)

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1],0:2] =>', array4)

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] => [3 6]
array2d[[0,1],0:2] => [[1 2]
 [4 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


##### 불린 인덱싱(Boolean indexing)

In [34]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [35]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [37]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [38]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


#### 행렬의 정렬 - sort()와 argsort()

In [39]:
## 행렬 정렬
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

## np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np_sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array) ## 원본 행렬이 바뀌지 않음

## ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array) ## 원본 행렬이 바뀜

원본 행렬: [3 1 9 5]
np_sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [40]:
## 내림차순으로 정렬 -- [::-1] 적용
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [41]:
## 2차원 이상일 경우
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0) ## ∨ 방향으로 정렬
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1) ## --> 방향으로 정렬
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


##### 정렬된 행렬의 인덱스를 반환하기

In [42]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array) ## 기존 원본 행렬의 원소에 대한 인덱스 반환
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [43]:
## 내림차순으로 정렬 시
sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices_desc))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [45]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


#### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

##### 행렬 내적(행렬곱)

In [46]:
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[7,8],
              [9,10],
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


##### 전치 행렬

In [47]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
